branches:
    - .*
matrix:
    - env: MONKEBASE_CONNECTION=imonke@unix(/run/mysqld/mysqld.sock)/imonke
      image: golang:latest
    - env: MONKEBASE_CONNECTION=imonke@unix(/run/mysqld/mysqld.sock)/imonke
      image: golang:1.15
    - env: MONKEBASE_CONNECTION=imonke@unix(/run/mysqld/mysqld.sock)/imonke
      image: golang:1.14
    - env: MONKEBASE_CONNECTION=imonke@unix(/run/mysqld/mysqld.sock)/imonke
      image: golang:1.13
before_script:
    - sudo apt-get update
    - sudo apt-get install -y mariadb-server mariadb-client git curl binutils bison gcc make
    - sudo service mysql start
    - sudo mysql -uroot -e"CREATE DATABASE imonke"
    - sudo mysql -uroot -e"CREATE USER 'imonke'@'localhost'"
    - sudo mysql -uroot -e"GRANT ALL PRIVILEGES ON imonke.* TO 'imonke'@'localhost'"
script:
    - go test ./... -cover -count 1
